version: '3.8'

services:
  postgres-gameteca:
    image: postgres:15-alpine
    container_name: postgres_gameteca_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - gameteca-network

networks:
  gameteca-network:
    driver: bridge